### ISSUE TITLE
Diseño de la libreta para App

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-confident-students#2]
[EMPAQUETADO DE LA LIBRERÍA EN DDL PARA SU IMPLEMENTACIÓN EN UNA APP, SOBRE EL INGRESO EN EL PÓRTICO DEL INSTITUTO TECNOLÓGI.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-confident-students/files/14925767/EMPAQUETADO.DE.LA.LIBRERIA.EN.DDL.PARA.SU.IMPLEMENTACION.EN.UNA.APP.SOBRE.EL.INGRESO.EN.EL.PORTICO.DEL.INSTITUTO.TECNOLOGI.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
